Repository ProEpiDesenvolvimento/guardioes-api, pull requests merged in 2020-11, with the labels that each got.

#186 Feature/manager permissions
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/contents_controller.rb
  app/controllers/group_managers_controller.rb
  app/controllers/managers_controller.rb
  app/controllers/permissions_controller.rb
  app/controllers/registration_controller.rb
  app/controllers/symptoms_controller.rb
  app/controllers/syndromes_controller.rb
  app/controllers/users_controller.rb
  app/models/ability.rb
  app/models/admin.rb
  app/models/app.rb
  app/models/group_manager.rb
  app/models/manager.rb
  app/models/permission.rb
  app/serializers/manager_serializer.rb
  config/routes.rb
  db/migrate/20200927013233_add_feedback_messages.rb
  db/migrate/20201008155529_create_managers.rb
  db/migrate/20201009151550_remove_email_from_managers.rb
  db/migrate/20201009151629_add_devise_to_managers.rb
  db/migrate/20201009154456_add_manager_to_app.rb
  db/migrate/20201009160356_add_app_to_manager.rb
  db/migrate/20201012185741_remove_manager_to_app.rb
  db/migrate/20201022180420_create_permissions.rb
  db/migrate/20201106181545_add_manager_to_permission.rb
  db/migrate/20201106181728_add_group_manager_to_permission.rb
  db/migrate/20201106181915_add_admin_to_permission.rb
  db/schema.rb
  docker-compose.yml
  lib/tasks/dev.rake
  spec/controllers/messages_controller_spec.rb
  spec/controllers/pre_registers_controller_spec.rb
  spec/controllers/syndromes_controller_spec.rb
  spec/examples.txt
  spec/factories/admin.rb
  spec/factories/user.rb
  spec/models/manager_spec.rb
  spec/models/permission_spec.rb
  spec/models/syndrome_symptom_percentage_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/syndromes_spec.rb
  spec/support/controller_macros.rb
Labels: hacktoberfest-accepted

#198 Fix user list
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/serializers/panel_user_serializer.rb
  app/serializers/user_without_name_serializer.rb.rb
  config/initializers/pager_api.rb
  config/routes.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: hacktoberfest-accepted

#212 Returns admin name
  app/serializers/admin_serializer.rb
Labels: enhancement

#211 Fix Syndrome edition
  app/serializers/syndrome_serializer.rb
  db/schema.rb
Labels: enhancement

#214 Managers Permissions
  app/controllers/managers_controller.rb
  app/serializers/group_manager_serializer.rb
Labels: enhancement

#220 Conserta erro ao deletar gerente de instituição
  app/controllers/group_managers_controller.rb
Labels: bug
