Repository ProEpiDesenvolvimento/guardioes-api, pull requests merged in 2020-10, with the labels that each got.

#175 Fixing vigilance
  app/mailers/vigilance_mailer.rb
  app/models/survey.rb
  app/views/vigilance_mailer/covid_vigilance_email.html.erb
Labels: bug, hacktoberfest-accepted

#177 Fix error on user's first survey
  app/controllers/groups_controller.rb
  app/models/user.rb
Labels: bug, hacktoberfest-accepted

#184 Melhora a feature de gamificação
  app/controllers/messages_controller.rb
  app/controllers/surveys_controller.rb
  app/models/user.rb
  app/serializers/household_serializer.rb
  app/serializers/message_serializer.rb
  db/migrate/20201020203908_add_day_to_messages.rb
  db/migrate/20201021181235_add_streak_to_household.rb
  db/schema.rb
Labels: enhancement, hacktoberfest-accepted

#190 Feature/app twitter
  app/controllers/apps_controller.rb
  app/controllers/groups_controller.rb
  app/controllers/registration_controller.rb
  app/models/group.rb
  app/serializers/app_serializer.rb
  config/routes.rb
  db/migrate/20201028155712_add_twitter_to_app.rb
  db/schema.rb
  lib/tasks/dev.rake
  spec/models/group_spec.rb
Labels: hacktoberfest-accepted
