Repository ProEpiDesenvolvimento/guardioes-api, pull requests merged in 2021-09, with the labels that each got.

#333 Adding offset to coordinates in surveyForMapSerializer
  app/models/survey.rb
  app/serializers/survey_for_map_serializer.rb
Labels: bug, help wanted

#334 Removing GroupManager permissions from response.
  app/models/group_manager_team.rb
  app/serializers/group_manager_serializer.rb
Labels: bug, help wanted

#336 Add additional logic for Forms
  app/controllers/form_questions_controller.rb
  app/controllers/forms_controller.rb
  app/models/form.rb
  app/models/form_question.rb
Labels: enhancement

#337 Add Vaccination to data_visualization
  app/controllers/data_visualizations_controller.rb
Labels: documentation
